export const PAL = {
  '.': null,
  b: '#7A6048',
  w: '#F4EEDC',
  t: '#D9B79D',
  k: '#2A2622',
  g: '#AFC979',
  q: '#7BA653',
  p: '#D8B7DC',
  a: '#D19A82',
  h: '#FFD85A',
  l: '#EAB896',
  v: '#B87961',
  y: '#E8D56E',
  r: '#C96F7D',
  s: '#E4A23A',
  d: '#A9B4BA',
  o: '#B9854E',
  c: '#5B3A24',
  j: '#B83B2E',
  m: '#8FBEB6',
  e: '#F0CE7A',
  u: '#CFC8B8',
  i: '#4FA3D1',
  n: '#A6DBF2',
};

export const SPRITE = [
  '.................bbb.........bbb................',
  '................bbwbb.......bbwbb...............',
  '................bwwwb.......bwwwb...............',
  '...............bbwwwbb.....bbwwwbb..............',
  '...............bwwwwwb.....bwwwwwb..............',
  '...............bwwwwwb.....bwwwwwb..............',
  '...............bwwwwwb.....bwwwwwb..............',
  '...............bwwwwwb.....bwwwwwb..............',
  '...............bwwwwwb.....bwwwwwb..............',
  '..............bbwwwwwbb...bbwwwwwbb.............',
  '..............bwwwwwwwb...bwwwwwwwb.............',
  '..............bwwwwwwwb...bwwwwwwwb.............',
  '..............bwwwwwwwbbbbbwwwwwwwb.............',
  '..............bwwwwwwwbwwwbwwwwwwwb.............',
  '..............bwwwwwwwwwwwwwwwwwwwb.............',
  '..............bbwwwwwwwwwwwwwwwwwbb.............',
  '...............bwwwwwwwwwwwwwwwwwb..............',
  '...............bwwwwwkkwwwkkwwwwwb..............',
  '...............bwwwwwkkwwwkkwwwwwb..............',
  '...............bwwwwwwwtttwwwwwwwb..............',
  '...............bwwwwwttkktttwwwwwb..............',
  '...............bwwwwtttkkttttwwwwb..............',
  '...............bbwwwtttttttttwwwbb..............',
  '................bwwtttktttktttwwb...............',
  '................bbwwtttkkktttwwbb...............',
  '.................bbwtttttttttwbb................',
  '.................brrtttttttttrrb................',
  '................bbrrrtttttttrrrbb...............',
  '........bbbbb..bbrrrrrrrtrrrrrrrbb..bbbbb.......',
  '....bbbbbgggbbbbrrrrrrrrrrrrrrrrrbbbbpppbbbbb...',
  '.bbbbggggggggggggrrrrrrrrrrrrrrrppppppppppppbbbb',
  'bbwgggggggggggggggrrrrrrrrrrrrrpppppppppppppppwb',
  'wwwwwggggggggggggggggygrrrpyppppppppppppppppwwww',
  'wwwwwwgggggggggggggggrrgpprrpppppppppppppppwwwww',
  'wwwwwggggggggggggggggrrgpprrppppppppppppppppwwww',
  'bbwgggggggggggggggggggggppppppppppppppppppppppwb',
  '.bbbbgggggggggggggggggggppppppppppppppppppppbbbb',
  '....bbbbbgggbbbbggggggggpppppppppbbbbpppbbbbb...',
  '........bbbbb..bggggggggpppppppppb..bbbbb.......',
  '...............byyyyyyyyrrrrrrrrrb..............',
  '...............byyyyyyyyrrrrrrrrrb..............',
  '...............byyyyyyyyrrrrrrrrrb..............',
  '...............byyyyyyyyrrrrsrrrrb..............',
  '...............byyyyyyyyrrrdssrrrb..............',
  '...............byyyyyyyyrrssyssrrb..............',
  '...............byyyyyyyyrrrssdrrrb..............',
  '...............byyyyyyyyrrrrsrrrrb..............',
  '...............byyyyyyyyrrrrrrrrrb..............',
  '...............byyyyyyyyrrrrrrrrrb..............',
  '...............byyyyyyyyrrrrrrrrrb..............',
  '...............byyyyyyyyrrrrrrrrrb..............',
  '...............byyyyyyyyrrrrrrrrrb..............',
  '...............byywyyyyyrrrrrrwrrb..............',
  '..............bbwwwwwyyyrrrrwwwwwbb.............',
  '..............bwwwwwwwyyrrrwwwwwwwb.............',
  '..............bbwwwwwbbbbbbbwwwwwbb.............',
  '...............bbbwbbb.....bbbwbbb..............',
  '.................bbb.........bbb................',
  '................................................',
  '................................................',
];

export const FACE = {
  sleep: [
    [21, 17, 'w'],
    [22, 17, 'w'],
    [21, 18, 'w'],
    [22, 18, 'w'],
    [26, 17, 'w'],
    [27, 17, 'w'],
    [26, 18, 'w'],
    [27, 18, 'w'],
    [21, 18, 'k'],
    [22, 18, 'k'],
    [26, 18, 'k'],
    [27, 18, 'k'],
  ],
};
FACE.blink = FACE.sleep;
